'use client';

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Tag } from '@carbon/react';
import {
  Notebook,
  Code,
  Document,
  ChartHistogram,
  Terminal,
  Settings,
} from '@carbon/icons-react';

interface AnatomyPart {
  id: string;
  name: string;
  badge: string;
  whatItIs: string;
  whyItExists: string;
  whatItDoes: string;
}

const anatomyParts: Record<string, AnatomyPart> = {
  header: {
    id: 'header',
    name: 'Notebook Header & Kernel Indicator',
    badge: 'Environment Control',
    whatItIs: 'The top bar showing the notebook file name, toolbar actions (Run, Stop, Restart), and active Kernel state indicator.',
    whyItExists: 'Allows you to control the background computing process, save your document, and monitor whether the Python engine is busy or idle.',
    whatItDoes: 'Provides 1-click controls to restart memory, interrupt runaway loops, or run all cells sequentially.',
  },
  markdown: {
    id: 'markdown',
    name: 'Markdown Cell (Narrative Layer)',
    badge: 'Documentation',
    whatItIs: 'A text cell formatted using lightweight Markdown syntax that renders into clean typography.',
    whyItExists: 'Data Science is about storytelling. Code alone does not explain why you chose a threshold, what hypothesis you tested, or what the findings mean.',
    whatItDoes: 'Renders formatted headings (#), bullet lists, bold text, equations, and tables directly above or below code.',
  },
  code: {
    id: 'code',
    name: 'Code Cell (Computational Layer)',
    badge: 'Executable Logic',
    whatItIs: 'An interactive Python editor cell with an execution prompt like In [1]:.',
    whyItExists: 'Enables chunked, modular coding where you can test small pieces of logic without running the entire application.',
    whatItDoes: 'Transmits code over WebSockets to the Python Kernel when you press Shift + Enter, computing results and updating memory.',
  },
  output: {
    id: 'output',
    name: 'Output Area (Result Layer)',
    badge: 'Computed Output',
    whatItIs: 'The clean container attached immediately below a code cell displaying text, return values, or print outputs.',
    whyItExists: 'Eliminates switching between a terminal window and an editor; your results stay permanently linked to the code that generated them.',
    whatItDoes: 'Renders stdout text, formatted pandas DataFrames, error tracebacks, or numeric calculations.',
  },
  visual: {
    id: 'visual',
    name: 'Visualization Area (Visual Analytics)',
    badge: 'Graphic Output',
    whatItIs: 'An embedded inline chart or plot generated by libraries like Matplotlib, Seaborn, or Plotly.',
    whyItExists: 'Visual inspection reveals patterns, outliers, skewness, and distributions that raw numbers cannot convey.',
    whatItDoes: 'Renders high-resolution vector or raster plots directly inside the notebook flow for instant stakeholder presentation.',
  },
};

export function NotebookAnatomyExplorer() {
  const [selectedPartId, setSelectedPartId] = useState<string>('code');
  const part = anatomyParts[selectedPartId];

  return (
    <div
      className="ds-glass-panel"
      style={{
        padding: '2rem',
        borderRadius: '4px',
        margin: '2.5rem 0',
        border: '1px solid var(--ds-border-strong)',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '1.25rem',
          flexWrap: 'wrap',
          gap: '8px',
        }}
      >
        <div>
          <span
            style={{
              fontFamily: 'var(--ds-font-mono)',
              fontSize: '0.75rem',
              color: 'var(--ds-cyan)',
              textTransform: 'uppercase',
            }}
          >
            Interactive Experience 2
          </span>
          <h3
            style={{
              fontSize: '1.375rem',
              fontWeight: 600,
              color: 'var(--ds-text-primary)',
              margin: '2px 0 0 0',
            }}
          >
            Anatomy of a Jupyter Notebook
          </h3>
        </div>
        <Tag type="cyan" size="md">
          Visual Dissector
        </Tag>
      </div>

      <p style={{ fontSize: '0.9375rem', color: 'var(--ds-text-secondary)', marginBottom: '1.5rem', lineHeight: 1.5 }}>
        Click any region of the simulated notebook mockup to inspect what it is, why it exists, and how it works:
      </p>

      {/* 2-Column Dissector Layout */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
          gap: '1.5rem',
          alignItems: 'start',
        }}
      >
        {/* Left: Interactive Mockup */}
        <div
          style={{
            background: 'var(--ds-bg-surface-elevated)',
            border: '1px solid var(--ds-border-strong)',
            borderRadius: '4px',
            overflow: 'hidden',
          }}
        >
          {/* 1. Mockup Header */}
          <div
            onClick={() => setSelectedPartId('header')}
            style={{
              padding: '10px 14px',
              background: selectedPartId === 'header' ? 'var(--ds-cyan-dim)' : 'var(--ds-bg-surface)',
              borderBottom: selectedPartId === 'header' ? '2px solid var(--ds-cyan)' : '1px solid var(--ds-border-subtle)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              cursor: 'pointer',
              transition: 'all 0.15s ease',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Notebook size={16} style={{ color: 'var(--ds-cyan)' }} />
              <span style={{ fontSize: '0.8125rem', fontWeight: 600, color: 'var(--ds-text-primary)' }}>
                student_analysis.ipynb
              </span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <div style={{ width: 8, height: 8, borderRadius: '50%', background: 'var(--ds-emerald)' }} />
              <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-text-muted)' }}>
                Python 3 (Idle)
              </span>
            </div>
          </div>

          <div style={{ padding: '12px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {/* 2. Mockup Markdown Cell */}
            <div
              onClick={() => setSelectedPartId('markdown')}
              style={{
                padding: '10px 12px',
                background: selectedPartId === 'markdown' ? 'var(--ds-purple-dim)' : 'var(--ds-bg-surface)',
                border: selectedPartId === 'markdown' ? '2px solid var(--ds-purple)' : '1px solid var(--ds-border-subtle)',
                borderRadius: '4px',
                cursor: 'pointer',
              }}
            >
              <div style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-purple)', marginBottom: '4px' }}>
                [MARKDOWN CELL]
              </div>
              <div style={{ fontSize: '0.9375rem', fontWeight: 700, color: 'var(--ds-text-primary)' }}>
                # 📊 Class Marks Analysis
              </div>
              <div style={{ fontSize: '0.75rem', color: 'var(--ds-text-secondary)', marginTop: '2px' }}>
                Calculating summary statistics for 10 engineering students.
              </div>
            </div>

            {/* 3. Mockup Code Cell */}
            <div
              onClick={() => setSelectedPartId('code')}
              style={{
                padding: '10px 12px',
                background: selectedPartId === 'code' ? 'var(--ds-cyan-dim)' : 'var(--ds-bg-surface)',
                border: selectedPartId === 'code' ? '2px solid var(--ds-cyan)' : '1px solid var(--ds-border-subtle)',
                borderRadius: '4px',
                cursor: 'pointer',
              }}
            >
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-cyan)' }}>
                  In [1]:
                </span>
                <Tag type="cyan" size="sm">Code Cell</Tag>
              </div>
              <div style={{ fontFamily: 'var(--ds-font-mono)', fontSize: '0.8125rem', color: 'var(--ds-text-primary)' }}>
                <div>marks = [78, 85, 92, 67, 74]</div>
                <div>average = sum(marks) / len(marks)</div>
                <div>average</div>
              </div>
            </div>

            {/* 4. Mockup Output Area */}
            <div
              onClick={() => setSelectedPartId('output')}
              style={{
                padding: '8px 12px',
                background: selectedPartId === 'output' ? 'rgba(36, 161, 72, 0.15)' : 'var(--ds-bg-surface)',
                border: selectedPartId === 'output' ? '2px solid var(--ds-emerald)' : '1px solid var(--ds-border-subtle)',
                borderRadius: '4px',
                cursor: 'pointer',
              }}
            >
              <div style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-emerald)', marginBottom: '2px' }}>
                Out [1]:
              </div>
              <div style={{ fontFamily: 'var(--ds-font-mono)', fontSize: '0.9375rem', fontWeight: 700, color: 'var(--ds-text-primary)' }}>
                79.2
              </div>
            </div>

            {/* 5. Mockup Visual Area */}
            <div
              onClick={() => setSelectedPartId('visual')}
              style={{
                padding: '10px 12px',
                background: selectedPartId === 'visual' ? 'rgba(69, 137, 245, 0.15)' : 'var(--ds-bg-surface)',
                border: selectedPartId === 'visual' ? '2px solid #4589f5' : '1px solid var(--ds-border-subtle)',
                borderRadius: '4px',
                cursor: 'pointer',
              }}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: '#4589f5' }}>
                  [VISUALIZATION OUTPUT]
                </span>
                <ChartHistogram size={16} style={{ color: '#4589f5' }} />
              </div>
              <div style={{ height: '36px', background: 'var(--ds-bg-surface-elevated)', borderRadius: '3px', display: 'flex', alignItems: 'flex-end', gap: '6px', padding: '4px' }}>
                <div style={{ width: '20%', height: '60%', background: 'var(--ds-cyan)', borderRadius: '2px' }} />
                <div style={{ width: '20%', height: '85%', background: 'var(--ds-teal)', borderRadius: '2px' }} />
                <div style={{ width: '20%', height: '100%', background: 'var(--ds-purple)', borderRadius: '2px' }} />
                <div style={{ width: '20%', height: '40%', background: 'var(--ds-emerald)', borderRadius: '2px' }} />
                <div style={{ width: '20%', height: '70%', background: '#4589f5', borderRadius: '2px' }} />
              </div>
            </div>
          </div>
        </div>

        {/* Right: Detailed Inspection Card */}
        <AnimatePresence mode="wait">
          <motion.div
            key={part.id}
            initial={{ opacity: 0, x: 10 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -10 }}
            transition={{ duration: 0.15 }}
            style={{
              padding: '1.5rem',
              background: 'var(--ds-bg-surface)',
              border: '1px solid var(--ds-border-strong)',
              borderRadius: '4px',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '1rem', flexWrap: 'wrap', gap: '8px' }}>
              <h4 style={{ fontSize: '1.125rem', fontWeight: 600, color: 'var(--ds-text-primary)', margin: 0 }}>
                {part.name}
              </h4>
              <Tag type="purple" size="md">{part.badge}</Tag>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              <div>
                <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-cyan)', textTransform: 'uppercase', display: 'block', marginBottom: '2px' }}>
                  1. WHAT IT IS
                </span>
                <p style={{ fontSize: '0.875rem', color: 'var(--ds-text-secondary)', margin: 0, lineHeight: 1.5 }}>
                  {part.whatItIs}
                </p>
              </div>

              <div>
                <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-teal)', textTransform: 'uppercase', display: 'block', marginBottom: '2px' }}>
                  2. WHY IT EXISTS
                </span>
                <p style={{ fontSize: '0.875rem', color: 'var(--ds-text-secondary)', margin: 0, lineHeight: 1.5 }}>
                  {part.whyItExists}
                </p>
              </div>

              <div>
                <span style={{ fontSize: '0.6875rem', fontFamily: 'var(--ds-font-mono)', color: 'var(--ds-emerald)', textTransform: 'uppercase', display: 'block', marginBottom: '2px' }}>
                  3. WHAT IT DOES
                </span>
                <p style={{ fontSize: '0.875rem', color: 'var(--ds-text-secondary)', margin: 0, lineHeight: 1.5 }}>
                  {part.whatItDoes}
                </p>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}
